### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by zgabi**
Could you please check whether this is ok for you.
Thanks.

I'll continue it next week if it is ok.

### CODE REVIEW

**Comment by zgabi** [comment]
Maybe easier to compare if you ignore the whitespace changes:
https://github.com/judero01col/GMap.NET/pull/69/files?w=1

But still a lot of changes.

**Comment by judero01col** [comment]
thanks for your contribution

**Comment by judero01col** [comment]
I would like to add it as a repository collaborator, I would like to know what you think of that?

**Comment by zgabi** [comment]
You want to add me as a collaborator? I'd be happy to help improving this project:)

**Pull request merged**
